package Constants

object CpgSchemaConstants {

  val CPG_BASE_PACKAGE_NAME = "io.shiftleft.codepropertygraph.generated"

  val CPG_DOMAIN_SHORT_NAME = "Cpg"

  val MY_PROPERTY_NAME = "MYPROPERTY"

  val MY_NODE_TYPE_NAME = "MYNODETYPE"

  val MY_PASSWORD_NAME = "PASSWORD"

  val AWS_KEYS_NAME = "AWS_KEYS"

  val IS_CREDENTIAL_NAME = "IS_CREDENTIAL"

  val CREDENTIAL_NODE_NAME = "CREDENTIALS"

  val JAVA_PROPERTY_NODE_NAME = "JAVA_PROPERTY"

  val IS_USED_AT_EDGE_NAME = "IS_USED_AT"

  val ORIGINAL_PROPERTY_EDGE_NAME = "ORIGINAL_PROPERTY"

  val MODULE_GROUP_ID_NAME = "groupId"

  val MODULE_ARTIFACT_ID_NAME = "artifactId"

  val MODULE_CONFIG_VERSION_NAME = "version"

  val MODULE_NODE_NAME = "MODULE"

  val MODULE_DEPENDENCY_NODE_NAME = "MODULE_DEPENDENCY"

  val MODULE_DEPENDENCY_EDGE_NAME = "DEPENDENCIES"

  val MANDATORY_EMPTY_VALUE = ""

}
