name: Monitoring Stability and Comparing Results
## Heyy, comparison-result-generation branch identity

# Triggers when a pull_request or a push action is configured on master branch
on:
  pull_request:
    branches: ["main", "comparison-result-generation"]

jobs:
  build_privado:
    strategy:
      matrix:
        owner: ["karan-batavia"]
        ref: ["${{github.head_ref}}", "${{github.base_ref}}"]
          
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
          
      - name: Install JDK-18
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'

      - name: Export Java Home Path
        run: export PATH=$JAVA_HOME/bin:$PATH

      - name: Install sbt
        run: mkdir -p ~/bin && curl -Ls https://raw.githubusercontent.com/dwijnand/sbt-extras/master/sbt > ~/bin/sbt && chmod 0755 ~/bin/sbt

      - name: Clone privado-core/${{matrix.ref}}
        uses: actions/checkout@v2
        with:
          owner: ${{matrix.owner}}
          repository: ${{matrix.owner}}/privado-core
          path: ./temp/${{matrix.ref}}
          ref: ${{matrix.ref}} 
      
      # - name: Check file contents
      #   run: ls -l ${GITHUB_WORKSPACE}/temp/

      - name: Build Privado binary for ${{matrix.ref}} branch
        run: cd ${GITHUB_WORKSPACE}/temp/${{matrix.ref}} && ~/bin/sbt -java-home $JAVA_HOME clean && ~/bin/sbt -java-home $JAVA_HOME stage 

      - name: Upload privado binary for next job
        uses: actions/upload-artifact@master
        with:
          name: ${{matrix.ref}}-binary
          path: /home/runner/work/privado-core/privado-core/temp/${{matrix.ref}}/target/universal/stage

  scan_repositories:
    needs: build_privado
    strategy:
      matrix:
        owner: ["Privado-Demo"]
        repo_name:
          [
            "privado-analytics",
            "privado-accounts-api",
            "shift-privacy-left-app",
          ]

    continue-on-error: true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install JDK-18
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'

      - name: Export Java Home Path
        run: export PATH=$JAVA_HOME/bin:$PATH

      # - name: Java path
      #   run: echo $JAVA_HOME

      # - name: check java version
      #   run: java -version

      # - name: check javac version 
      #   run: javac -version

      - name: Clone Privado-Inc/privado
        uses: actions/checkout@v2
        with:
          owner: "Privado-Inc"
          repository: "Privado-Inc/privado"
          path: ./privado-core-and-rules/privado


      - name: Download base binary 
        uses: actions/download-artifact@master
        with:
          name: ${{github.base_ref}}-binary
          path: ./privado-core-and-rules/${{github.base_ref}}/privado-core-binary

      - name: Download head binary 
        uses: actions/download-artifact@master
        with:
          name: ${{github.head_ref}}-binary
          path: ./privado-core-and-rules/${{github.head_ref}}/privado-core-binary

      # - name: Check contents (base)
      #   run: ls ./privado-core-and-rules/${{github.base_ref}}/privado-core-binary && ls -l
      
      # - name: Check contents (head)
      #   run: ls ./privado-core-and-rules/${{github.head_ref}}/privado-core-binary && ls -l

      - name: Create Folder to store reports
        run: mkdir ${GITHUB_WORKSPACE}/reports && mkdir ${GITHUB_WORKSPACE}/${{matrix.repo_name}}_results/${{github.base_ref}} && mkdir ${GITHUB_WORKSPACE}/${{matrix.repo_name}}_results/${{github.head_ref}} && mkdir ${GITHUB_WORKSPACE}/time_results

      - name: Trigger metadata
        run: echo " {\"pr_branch\":\"${{github.head_ref}}\", \"push_branch\":\"${{github.ref_name}}\", \"prNumber\":\"${{github.event.number}}\", \"commitID\":\"${GITHUB_SHA}\"}" > ${GITHUB_WORKSPACE}/reports/trigger_metadata.json && cat ${GITHUB_WORKSPACE}/reports/trigger_metadata.json

      - name: Download CPU and Memory usage capture tool
        run: mkdir ${GITHUB_WORKSPACE}/tools && curl https://raw.githubusercontent.com/Privado-Inc/privado-core-results-monitoring/main/capture_usage.sh --output ${GITHUB_WORKSPACE}/tools/capture_usage.sh

      - name: Start monitoring cpu and memory usage
        run: bash ${GITHUB_WORKSPACE}/tools/capture_usage.sh &

      # Setup python 3.8 in the pipeline
      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      # Setup privado environment in the pipeline
      - name: Setup Privado Env
        run: curl -o- https://raw.githubusercontent.com/Privado-Inc/privado-cli/main/install.sh | bash

      - name: Clone repository
        uses: actions/checkout@v2
        with:
          owner: ${{matrix.owner}}
          repository: ${{matrix.owner}}/${{matrix.repo_name}}
          path: ./repos/${{matrix.repo_name}}

      - name: change permission of stable privado-core
        run: chmod 777 ${GITHUB_WORKSPACE}/privado-core-and-rules/${{github.base_ref}}/privado-core-binary/bin/privado-core

      - name: change permission of dev privado-core
        run: chmod 777 ${GITHUB_WORKSPACE}/privado-core-and-rules/${{github.head_ref}}/privado-core-binary/bin/privado-core

      # - name: simple scan using
      #   run: cd ${GITHUB_WORKSPACE}/privado-core-and-rules/${{github.base_ref}}/privado-core/target/universal/stage/bin && ./privado-core scan ${GITHUB_WORKSPACE}/repos/${{matrix.repo_name}} -ic ${GITHUB_WORKSPACE}/privado-core-and-rules/privado --skip-upload

      - name: Scan ${{matrix.owner}}/${{matrix.repo_name}} (${{github.base_ref}}) using privado scan
        run: cd ${GITHUB_WORKSPACE}/privado-core-and-rules/${{github.base_ref}}/privado-core-binary/bin && { time ./privado-core scan ${GITHUB_WORKSPACE}/repos/${{matrix.repo_name}} -ic ${GITHUB_WORKSPACE}/privado-core-and-rules/privado --skip-upload; } 2> ${GITHUB_WORKSPACE}/time_results/${{matrix.repo_name}}_time_${{github.base_ref}}.txt

      - name: Store ${{matrix.repo_name}}.json (${{github.base_ref}})
        run: cat ${GITHUB_WORKSPACE}/repos/${{matrix.repo_name}}/.privado/privado.json > ${GITHUB_WORKSPACE}/${{matrix.repo_name}}_results/${{github.base_ref}}/privado.json

      - name: Scan ${{matrix.owner}}/${{matrix.repo_name}} (${{github.head_ref}}) using privado scan
        run: cd ${GITHUB_WORKSPACE}/privado-core-and-rules/${{github.head_ref}}/privado-core-binary/bin && { time ./privado-core scan ${GITHUB_WORKSPACE}/repos/${{matrix.repo_name}} -ic ${GITHUB_WORKSPACE}/privado-core-and-rules/privado --skip-upload; } 2> ${GITHUB_WORKSPACE}/time_results/${{matrix.repo_name}}_time_${{github.head_ref}}.txt

      - name: Store ${{matrix.repo_name}}.json (${{github.head_ref}})
        run: cat ${GITHUB_WORKSPACE}/repos/${{matrix.repo_name}}/.privado/privado.json > ${GITHUB_WORKSPACE}/${{matrix.repo_name}}_results/${{github.head_ref}}/privado.json

      - name: Pass JSON (${{github.base_ref}}) to the next job
        uses: actions/upload-artifact@master
        with:
          name: ${{matrix.repo_name}}_stable
          path: ${GITHUB_WORKSPACE}/${{matrix.repo_name}}_results/${{github.base_ref}}/privado.json

      - name: Pass JSON (${{github.head_ref}}) to the next job
        uses: actions/upload-artifact@master
        with:
          name: ${{matrix.repo_name}}_dev
          path: ${GITHUB_WORKSPACE}/${{matrix.repo_name}}_results/${{github.head_ref}}/privado.json
          
      - name: Upload CPU and memory usage file
        uses: actions/upload-artifact@master
        with:
          name: ${{matrix.repo_name}}_cpu
          path: ${GITHUB_WORKSPACE}/tools/results_1.txt

      - name: Upload time stats for repos
        uses: actions/upload-artifact@master
        with:
          name: ${{matrix.repo_name}}_time
          path: ${GITHUB_WORKSPACE}/time_results

      - name: Upload Trigger metadata
        uses: actions/upload-artifact@master
        with:
          name: ${{matrix.repo_name}}_trigger
          path: ${GITHUB_WORKSPACE}/reports/trigger_metadata.json

  # compare_and_send_reports:
  #   needs: scan_repositories
    
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/download-artifact@master
  #       with:
  #         path: ./results

  #     - name: Download the comparison tool
  #       run: curl https://raw.githubusercontent.com/Privado-Inc/privado-core-results-monitoring/main/compare.py --output ${GITHUB_WORKSPACE}/compare.py

  #     - name: Check contents of folder
  #       run: cd ./results/privado-analytics_time/ && ls -lha

  #     - name: stable content
  #       run: cat ./results/privado-accounts-api_time/privado-accounts-api_time_stable.txt

  #     - name: dev content
  #       run: cat ./results/privado-accounts-api_time/privado-accounts-api_time_dev.txt

  #     - name: Compare the two results (privado-analytics)
  #       run: python ./compare.py ./results/privado-analytics_stable/privado-analytics.json ./results/privado-analytics_dev/privado-analytics.json ./results/privado-analytics_cpu/results_1.txt ./results/privado-analytics_trigger/trigger_metadata.json ./results/privado-accounts-api_time/privado-accounts-api_time_stable.txt ./results/privado-analytics_time/privado-analytics_time_dev.txt

  #     - name: Compare the two results (privado-accounts-api)
  #       run: python ./compare.py ./results/privado-accounts-api_stable/privado-accounts-api.json ./results/privado-accounts-api_dev/privado-accounts-api.json ./results/privado-accounts-api_cpu/results_1.txt ./results/privado-accounts-api_trigger/trigger_metadata.json ./results/privado-accounts-api_time/privado-accounts-api_time_stable.txt ./results/privado-accounts-api_time/privado-accounts-api_time_dev.txt

  #     - name: Compare the two results (shift-privacy-left-app)
  #       run: python ./compare.py ./results/shift-privacy-left-app_stable/shift-privacy-left-app.json ./results/shift-privacy-left-app_dev/shift-privacy-left-app.json ./results/shift-privacy-left-app_cpu/results_1.txt ./results/shift-privacy-left-app_trigger/trigger_metadata.json ./results/shift-privacy-left-app_time/shift-privacy-left-app_time_stable.txt ./results/shift-privacy-left-app_time/shift-privacy-left-app_time_dev.txt

  #     - name: Post results to slack
  #       uses: MeilCli/slack-upload-file@v3
  #       with:
  #         slack_token: ${{ secrets.SLACK_TOKEN }}
  #         channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
  #         file_path: "/home/runner/work/privado-core/privado-core/comparison_report.csv"
  #         initial_comment: "Comparison Results generated on ${{github.event.repository.name}} by PR ${{github.event.number}} from branch ${{github.head_ref}} to ${{github.base_ref}}"
  #         file_type: "csv"
  
  # compare-and-send-reports: 
  #   needs: scan_repositories
  #   strategy:
  #     matrix:
  #       max_parallel: 1
  #       repo_name:
  #         [
  #           "privado-analytics",
  #           "privado-accounts-api",
  #           "shift-privacy-left-app",
  #         ]

  #   runs-on: ubuntu-latest
  #   steps: 

  #   - name: Download the comparison tool
  #     run: curl https://raw.githubusercontent.com/Privado-Inc/privado-core-results-monitoring/main/compare.py --output ${GITHUB_WORKSPACE}/compare.py

  #   - name: Download ${{github.base_ref}} JSON File (${{matrix.repo_name}}) 
  #   - uses: action/download-artifact@master
  #     with: 
  #       name: ${{matrix.repo_name}}_stable
  #       path: ${GITHUB_WORKSPACE}/${{matrix.repo_name}}/${{github.base_ref}}

  #   - name: Download ${{github.head_ref}} JSON File (${{matrix.repo_name}})
  #   - uses: action/download-artifact@master
  #     with: 
  #       name: ${{matrix.repo_name}}_dev
  #       path: ${GITHUB_WORKSPACE}/${{matrix.repo_name}}/{{github.head_ref}}

  #   - name: Download ${{github.head_ref}} Time Result (${{matrix.repo_name}})
  #   - uses: action/download-artifact@master
  #     with: 
  #       name: ${{matrix.repo_name}}_time
  #       path: ${GITHUB_WORKSPACE}/${{matrix.repo_name}}

  #   - name: Download ${{github.head_ref}} CPU and Memory Result (${{matrix.repo_name}})
  #   - uses: action/download-artifact@master
  #     with: 
  #       name: ${{matrix.repo_name}}_cpu
  #       path: ${GITHUB_WORKSPACE}/${{matrix.repo_name}}

  #   - name: Download ${{github.head_ref}} Trigger Metadata Result (${{matrix.repo_name}})
  #   - uses: action/download-artifact@master
  #     with: 
  #       name: ${{matrix.repo_name}}_trigger
  #       path: ${GITHUB_WORKSPACE}/${{matrix.repo_name}}

  #   - name: Compare Result (${{matrix.repo_name}})
  #     run: python ./compare.py ${GITHUB_WORKSPACE}/${{matrix.repo_name}}/${{github.base_ref}}/privado-analytics.json ${GITHUB_WORKSPACE}/${{matrix.repo_name}}/${{github.base_ref}}/privado-analytics.json ${GITHUB_WORKSPACE}/${{matrix.repo_name}}/results_1.txt ${GITHUB_WORKSPACE}/${{matrix.repo_name}}/trigger_metadata.json ${GITHUB_WORKSPACE}/${{matrix.repo_name}}/${{matrix.repo_name}}_time_${{github.base_ref}}.txt ${GITHUB_WORKSPACE}/${{matrix.repo_name}}/${{matrix.repo_name}}_time_${{github.base_ref}}.txt

  #   - name: print
  #     run: echo ${{strategy.job-total}}

    # - name: Post results to slack
    #   uses: MeilCli/slack-upload-file@v3
    #   if: strategy.job-index == strategy.job-total
    #   with:
    #     slack_token: ${{ secrets.SLACK_TOKEN }}
    #     channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
    #     file_path: "${{GITHUB_WORKSPACE}}/comparison_report.csv"
    #     initial_comment: "Comparison Results generated on ${{github.event.repository.name}} by PR ${{github.event.number}} from branch ${{github.head_ref}} to ${{github.base_ref}}"
    #     file_type: "csv"