name: Vulnerability Scan
on: pull_request_target
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.head_ref }}
      - run: export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} && docker build . -t privado-core-oss -f Dockerfile
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: privado-core-oss
          args: --severity-threshold=high